### ISSUE TITLE
未知原因在源码中`pack, err = c.getCurrent().NextReader()`处出现问题

### ISSUE THREAD

**Issue by Jolly23** [zhouhui8915/go-socket.io-client#12]
```golang
opts := &socketio_client.Options{
		Transport: "websocket",
		Query:     make(map[string]string),
	}
	uri := "https://ws.gate.io/socket.io/"

	client, err := socketio_client.NewClient(uri, opts)
	if err != nil {
		panic(err)
		return
	}
```

按照example，用这个地址连接，返回错误`invalid input`，我根据源码调试，发现已经获取到了sid等一系列信息。
在client_conn.go文件的325行`pack, err = c.getCurrent().NextReader()`返回了错误，有点迷惑

**Comment by Jolly23** [comment]
在建立连接前https post的时候有个payload需要发送，内容是`gateio_eth_usdt`，请问这个应该写到哪里？

**Comment by Jolly23** [comment]
<img width="776" alt="wx20180226-120523 2x" src="https://user-images.githubusercontent.com/17488831/36653009-67537d80-1aed-11e8-8d07-2e73cc1a0698.png">

**Comment by HaoweiCh** [comment]
请问你现在解决了吗？
